(function(){var g=void 0,l=true,m=null,o=false,r,t=this;function aa(){for(var a="",b=0;b<16;b++)a+=Math.random();return a}function u(a,b){var c="",d=ba(encodeURIComponent(a));d.splice(b||5,d.length);w(d,function(a,b){var d;d=b;if(d==0)d="A";else{d>>>=0;for(var i="",h;d>0;)h=d%64,i="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(h)+i,d>>>=6;d=i}c+=d});return c}
function ba(a){a+=String.fromCharCode(128);for(var b=[1518500249,1859775393,2400959708,3395469782],c=1732584193,d=4023233417,e=2562383102,f=271733878,k=3285377520,i=[],h,p,q,s,v,B=Math.ceil((a.length/4+2)/16),y=[B],n=0,j;n<B;n++){y[n]=[];for(h=0;h<16;h++)y[n][h]=a.charCodeAt(n*64+h*4)<<24|a.charCodeAt(n*64+h*4+1)<<16|a.charCodeAt(n*64+h*4+2)<<8|a.charCodeAt(n*64+h*4+3)}n=(a.length-1)*8;a=B-1;y[a][14]=Math.floor(n/Math.pow(2,32));y[a][15]=n&4294967295;for(n=0;n<B;n++){for(j=0;j<16;j++)i[j]=y[n][j];
for(j=16;j<80;j++)i[j]=(i[j-3]^i[j-8]^i[j-14]^i[j-16])<<1|(i[j-3]^i[j-8]^i[j-14]^i[j-16])>>>31;a=c;h=d;p=e;q=f;s=k;for(j=0;j<80;j++)v=Math.floor(j/20),v=(a<<5|a>>>27)+(v==0?h&p^~h&q:v==1?h^p^q:v==2?h&p^h&q^p&q:h^p^q)+s+b[v]+i[j]&4294967295,s=q,q=p,p=h<<30|h>>>2,h=a,a=v;c=c+a&4294967295;d=d+h&4294967295;e=e+p&4294967295;f=f+q&4294967295;k=k+s&4294967295}return[c,d,e,f,k]}function x(a,b){return function(){a.apply(b,arguments)}}
function z(a,b,c){a.addEventListener?a.addEventListener(b,c,o):a.attachEvent&&a.attachEvent("on"+b,c)}function A(a){a=new Date(+a);return Date.UTC(a.getFullYear(),a.getMonth(),a.getDate())}function C(){return(new Date).getTime()}function w(a,b){if((!!a&&a.constructor===Object)===l)for(var c in a){if(a.hasOwnProperty(c)&&b(c,a[c])===o)break}else{c=a.length;for(var d=0;d<c;d++)if(b(d,a[d])===o)break}}
function ca(a,b){if(a===b)return 0;if(a.length===0)return b.length;if(b.length===0)return a.length;for(var c=[],d=0,e=b.length;d<=e;d++)c[d]=[d];for(var f=0,k=a.length;f<=k;f++)c[0][f]=f;for(var i,h,p,d=1;d<=e;d++)for(f=1;f<=k;f++)i=d-1,h=f-1,p=c[i][h],b.charAt(i)==a.charAt(h)?c[d][f]=p:(h=c[d][h]+1,i=c[i][f]+1,p+=2,c[d][f]=Math.min(h,i,p));return c[b.length][a.length]};function D(){this.p=[];this.Q=o;this.F=this.j=m;this.q=[];E(this,t,"onscroll");E(this,document.body,"onkeydown");E(this,document.body,"onmousemove");this.g()}D.prototype.g=function(){this.l={};this.e=0;F(this);this.l.onmousemove=C()};function F(a){a.I&&clearInterval(a.I);a.O();a.I=setInterval(x(a.O,a),1E3)}
function E(a,b,c){var d=b[c]||function(){};a.q.push(c);b[c]=function(b){d.apply(this,arguments);if(b&&c=="onkeydown"){var f=b.keyCode?b.keyCode:b.which;if(f==32||f>36&&f<41){a.l.onscroll=C();return}}a.l[c]=C();if(a.Q)a.j===m&&a.H(),t.clearTimeout(a.F),a.F=t.setTimeout(x(a.H,a),500)}}D.prototype.H=function(){var a=this;this.j=t.setTimeout(function(){t.clearTimeout(a.j);a.j=m},500);for(var b=0,c=this.p.length;b<c;b++)if(typeof this.p[b]==="function")this.p[b]()};
function G(a,b,c){a=a.l[b];if(a===g)return o;a=C()-a;return a<=(c||15E3)&&a>=0}D.prototype.O=function(){var a;a:{a=0;for(var b=this.q.length;a<b;a++)if(G(this,this.q[a],5E3)){a=l;break a}a=o}a&&this.e++};function H(a){var b=a.e;a.e=0;F(a);return b};function J(a){var b={};if(a){a.charAt(0)=="?"&&(a=a.substring(1));for(var a=a.replace("+"," "),a=a.split(/[&;]/g),c=0,d=a.length;c<d;c++){var e=a[c].split("=");b[decodeURIComponent(e[0])]=decodeURIComponent(e[1])}}return b}function K(a,b,c){var d="",e=t.location.href.split("?");e.length&&(e=J(e[1]),b=c||b,e[b]&&(d="&"+a+"="+e[b]));return d};var L={};L.c=function(a){var b=t._sf_async_config;if(!a&&b&&b.noCookies)return m;if(L.c.s!==g)return L.c.s;var a=C()+"",c,d;try{if((d=t.localStorage).setItem(a,a),c=d.getItem(a)===a,d.removeItem(a),c)return L.c.s=d}catch(e){}return L.c.s=m};L.b=function(a){var b=L.c();if(!b)return"";var c=b.getItem(a+"_expires");return c&&(c=+c,!isNaN(c)&&C()>c)?(L.remove(a),""):b.getItem(a)||""};
L.create=function(a,b,c){var d=L.c();if(d){try{d.setItem(a,b)}catch(e){}b=new Date;b.setTime(C()+c*864E5);try{d.setItem(a+"_expires",b.getTime())}catch(f){}}};L.remove=function(a){var b=L.c();b&&(b.removeItem(a),b.removeItem(a+"_expires"))};var da=(document.location.protocol=="https:"?"https://a248.e.akamai.net/chartbeat.download.akamai.com/102508/":"http://static.chartbeat.com/")+"js/inpage.js";function M(){var a=document.createElement("script");a.async=l;a.src=da;var b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)}function ea(a){if(/[\/|\.]chartbeat\.com$/.test(a.origin)){var b=L.c(l),c=String(a.data);b&&c.indexOf("_cb_ip")==0&&(b.setItem("_cb_ip","1"),a.source.postMessage(1,a.origin),M())}};var N={b:function(a){a+="=";for(var b=document.cookie.split(";"),c,d=0,e=b.length;d<e;d++){for(c=b[d];c.charAt(0)===" ";)c=c.substring(1,c.length);if(c.indexOf(a)===0)return c.substring(a.length,c.length)}return""},create:function(a,b,c){var d=t._sf_async_config;if(!d||!d.noCookies)d=new Date,d.setTime(C()+c*864E5),document.cookie=a+"="+b+("; expires="+d.toGMTString())+"; path=/"}};N.remove=function(a){N.b(a)&&N.create(a,"",-1)};function O(a){this.m=a||"";this.D=o;fa(this)}
function fa(a){if(!N.b("_cb_ls")){var b=L.c()!==m,c=N.b("_SUPERFLY_nosample");c&&w(["","_v_","_p_"],function(b,d){a.create(d+"_SUPERFLY_nosample",c,0.007,l)});var d=N.b("_chartbeat3");d&&(a.create("_v__chartbeat3",d,30,l),N.remove("_chartbeat3"));b&&((b=N.b("_chartbeat2"))&&a.create("_chartbeat2",b,30,l),(b=N.b("_chartbeat_uuniq"))&&a.create("_chartbeat_uuniq",b,30,l),(b=N.b("_chartbeat5"))&&a.create("_chartbeat5",b,6.944444444444445E-4,l));N.create("_cb_ls","1",30)}}
function ga(a){var b=a.D;a.D=o;return b}O.prototype.create=function(a,b,c,d){a=d?a:this.m+a;(L.c()?L:N).create(a,b,c);L.c()&&N.create(a,b,c)};O.prototype.update=function(a,b,c,d,e,f){a=d?a:this.m+a;e=typeof e==="string"?e:"::";d=(d=this.b(a,l))?d.split(e):[];typeof f==="number"&&d.length>=f&&d.splice(0,d.length-f+1);d.push(b);this.create(a,d.join(e),c,l)};
O.prototype.b=function(a,b){var a=b?a:this.m+a,c=(L.c()?L:N).b(a);if(!c&&L.c()&&(c=N.b(a))&&N.b("_cb_ls")){this.D=l;var d;switch(a){case "_SUPERFLY_nosample":d=0.007;break;case "_chartbeat4":d=0.0417;break;case "_cb_cp":d=0.0417;break;default:d=30}L.create(a,c,d)}return c};O.prototype.remove=function(a,b){a=b?a:this.m+a;(L.c()?L:N).remove(a);L.c()&&N.remove(a)};function P(a){var b,c;b="pageYOffset";c="scrollTop";if(a){var d,e;d=d||"*";e=e||document;if("querySelectorAll"in e)a=e.querySelectorAll(d+"[data-cb-scroll-element]");else{a=[];d=e.getElementsByTagName(d);for(e=d.length;e--;)d[e].getAttribute("data-cb-scroll-element")&&a.push(d[e])}if(a&&a.length)return a[0][c]}if(typeof t[b]=="number")return t[b];else if(document.body&&document.body[c])return document.body[c];else if(document.documentElement[c])return document.documentElement[c];return 0}
function Q(){var a=document;return a[a.compatMode==="CSS1Compat"?"documentElement":"body"].clientHeight||0}function R(a){a="scroll"+a;return Math.max(document.body[a],document.documentElement[a])||0};function S(a){this.a=t._sf_async_config||{};this.R=x(this.W,this);this.i=[];this.k=a;this.d=new O(this.$);this.g();z(t,"unload",x(this.w,this));for(var a=x(this.Y,this),b=t._cbq||[];b.length;)a(b.shift());t._cbq={push:a}}r=S.prototype;r.g=function(){this.v=this.h=0;this.C=C();this.A=u(T(this,o));this.z=l;this.J=72E5;this.f=this.e=0;this.k.g();var a=+this.a.sessionLength;if(!isNaN(a))this.J=a*6E4};
function U(a){if(!a.d.b("_SUPERFLY_nosample"))a.T?a.B():(a.T=l,!t._sf_async_config&&!t._cbq?z(t,"load",x(a.B,a)):a.B())}r.B=function(){var a=t._sf_startpt,b=t._sf_endpt;if(typeof a=="number")this.M=typeof b=="number"?b-a:C()-a;this.u=setInterval(x(this.K,this),15E3);this.K()};
r.K=function(){this.f=H(this.k);this.e+=this.f;var a=this.a.reading&&+this.a.reading||this.f>0;this.v<this.h&&!a?this.v++:(a?this.h=0:V(this),this.v=0,this.i.push(0),this.i.length>18&&this.i.shift(),ha(this),C()-this.C>=this.J&&clearInterval(this.u))};function W(a,b){var c;c=new Image(1,1);c.onerror=a.R;c.src=b}r.W=function(){this.i.push(1);for(var a=0,b=0,c=this.i.length;b<c;++b)a+=this.i[b];a<3?(this.z=l,V(this)):(clearInterval(this.u),this.d.create("_SUPERFLY_nosample","1",0.007))};
r.w=function(){this.d.update("_cb_cp",this.A,0.0417,o,",")};r.Y=function(a){this.a[a[0]]=a[1];this.h=0};function V(a){var b=a.h,b=b?Math.min(b*2,16):1;a.h=b}r.Z=function(a,b){this.o=t.location.protocol+"//"+this.a.domain+this.a.path;this.a.path=a;b&&(this.a.title=b);clearInterval(this.u);this.g();U(this)};function X(a){if(a.o)return l;a=(document.referrer||"").indexOf("://"+t.location.host+"/");return a!=-1&&a<9}function Y(a){a=a.a.title.slice(0,100);return encodeURIComponent(a)}
function T(a,b){var c=t.navigator,d=t.window.screen,e=[c.userAgent,c.platform,(new Date).getTimezoneOffset(),d.width+d.height+d.colorDepth];w(c.plugins,function(a,b){e.push(b.name+b.description+b.filename+b[0].type)});if(b===o)c=t.performance,e=e.concat([c&&c.now?c.now():"",encodeURIComponent(a.o||document.referrer||""),document.title,t.location.href,C(),R("Width"),R("Height"),aa()]);return e.join()};function Z(a){S.call(this,a);z(document.body,"click",x(this.V,this))}(function(){var a=S;function b(){}b.prototype=a.prototype;Z.N=a.prototype;Z.prototype=new b;Z.prototype.constructor=Z})();r=Z.prototype;
r.g=function(){Z.N.g.call(this);this.r=m;for(var a=this.a,b=document.getElementsByTagName("script"),c=0,d=b.length;c<d;++c)if(b[c].src.match(/chartbeat.js/)){b=J(b[c].src.split("?")[1]);a.uid=a.uid||b.uid;a.domain=a.domain||b.domain;break}a=t.location;b=this.a;b.pingServer=b.pingServer||"ping.chartbeat.net";b=this.a;b.title=b.title||document.title;b=this.a;b.domain=b.domain||a.host;b=this.a;a:{c=m;if(this.a.useCanonical){for(var c=m,d=document.getElementsByTagName("link"),e=0,f=d.length;e<f;++e)if(d[e].rel==
"canonical")c=d[e].href,c=c.substring(c.indexOf("/",9));if(c)break a}e=t.location;c=e.pathname+(e.search||"");c=c.replace(/PHPSESSID=[^&]+/,"");d=/&utm_[^=]+=[^&]+/ig;(e=d.exec(e.search))&&(c=c.replace(d,""));d=/\?utm_[^=]+=[^&]+(.*)/i;(e=d.exec(c))&&(c=c.replace(d,e[1]!=""?"?"+e[1]:""))}b.path=b.path||c;this.t=a.host.replace(/^www\./,"");this.a.domain=this.a.domain.replace(/^www\./,"");a=(this.d.b("_chartbeat2",l)||"").split(".");b=C();c=b-+(a[1]||0);e="1";f=a&&+a[2];d=a&&a[3];if(a&&f&&d)if(e=Math.abs((A(b)-
A(f))/864E5)){e=Math.min(e,16)-1;for(f="";e--;)f+=0;e=(d+f+"1").slice(-16)}else e=d;d=e;this.U=a[0]&&c>18E5?0:1;a[0]||(a[0]=u(T(this,o),3),a[1]=b);a[2]=b;a[3]=d;this.n=a[0];this.X=a.join(".");this.d.create("_chartbeat2",this.X,30,l);this.a.utoken=this.n;var k;b=+a[1];c=+a[2];if((a=a[3])&&b&&c)k=(Math.min((Math.abs((A(c)-A(b))/864E5)||0)+1,16,a.length)-1).toString(16),k+=("0000"+parseInt(a,2).toString(16)).slice(-4);this.G=k;t.postMessage&&z(t,"message",x(this.S,this));k=this.d.b("_chartbeat_uuniq")===
"3";this.d.create("_chartbeat_uuniq","3",30);k||W(this,"//ping.chartbeat.net/uuniq?u="+this.n+"&u2="+u(T(this,l)))};r.P=function(a){this.r=a};r.w=function(){Z.N.w.call(this);this.f=H(this.k);this.e+=this.f;this.d.update("_chartbeat4",["t="+this.A,"E="+this.e,"x="+P(!!this.a.scrollElement),"c="+Math.round((C()-this.C)/600)/100,"y="+R("Height"),"w="+Q()].join("&"),0.0417)};
function ha(a){var b=a.a,c=P(!!b.scrollElement),d=Math.round((C()-a.C)/600)/100,e=0,f=0,k=0;G(a.k,"onkeydown")?f=1:a.a.reading&&+a.a.reading||a.f>0||d<0.09?e=1:k=1;var i="",h="",p="",q="",s=X(a);if(a.z){a.z=o;var i=(s?"&v=":"&r=")+encodeURIComponent(a.o||document.referrer||""),h="&i="+Y(a),v=a.a.hudTrackable;v!==g&&(p="&L="+(v?"1":"0"));if(s&&(s=ia(a)))i="&v="+encodeURIComponent(s.path),q="&K="+s.left+"::"+s.top,s.L>1&&(q+="&l1="+s.L)}var s=a.M?"&b="+a.M:"",v=a.r?"&A="+a.r:"",B=a.G?"&f="+a.G:"",y=
a.d.b("_cb_cp"),y=y?"&D="+y:"";a.d.remove("_cb_cp");var n="",j=a.d.b("_chartbeat4");j&&(w(j.split("::"),function(a,b){n+="&z="+encodeURIComponent(b)}),a.d.remove("_chartbeat4"));var j=[],I;for(I in b)I.charAt(0)=="_"&&j.push(I+"="+b[I]);W(a,(t.location.protocol||"http:")+"//"+b.pingServer+"/ping?h="+encodeURIComponent(b.domain)+"&p="+encodeURIComponent(b.path)+"&u="+a.n+"&d="+encodeURIComponent(a.t)+"&g="+b.uid+(b.sections?"&g0="+encodeURIComponent(b.sections):"")+(b.authors?"&g1="+encodeURIComponent(b.authors):
"")+(b.noCookies?"":"&n="+a.U)+B+"&c="+d+"&x="+c+"&y="+R("Height")+"&o="+R("Width")+"&w="+Q()+"&j="+Math.round((a.h+2)*15E3/1E3)+"&R="+e+"&W="+f+"&I="+k+"&E="+a.e+"&e="+a.f+i+q+s+v+K("C","utm_campaign",b.campaignTag)+K("M","utm_medium",b.mediumTag)+"&t="+a.A+"&V=21"+y+n+h+p+(ga(a.d)?"&l=1":"")+(j.length?"&"+j.join("&"):"")+"&_")}
r.S=function(a){var b=this.a;if(a.origin==="http://"+(b.playerdomain||this.t)){var c=a.data;if(typeof c=="string"&&c.indexOf("cbqpush::")===0){if(a=c.split("::"),a.length==3)a[1].indexOf("_")===0&&(b[a[1]]=a[2]),this.h=0}else c=="cbdata?"&&(b="domain="+encodeURIComponent(b.domain)+"&path="+encodeURIComponent(b.path)+"&title="+Y(this)+"&referrer="+encodeURIComponent(this.o||document.referrer||"")+"&internal="+(X(this)?"1":"0")+"&subdomain="+encodeURIComponent(this.t)+"&utoken="+this.n,a.source.postMessage(b,
"*"))}};
r.V=function(a){var b,c;if(a=a||window.event){c=a.target||a.srcElement;if(c.tagName!=="A")if(c.parentNode)if(c.parentNode.tagName==="A")c=c.parentNode;else{if(c.parentNode.parentNode&&c.parentNode.parentNode.tagName==="A")c=c.parentNode.parentNode}else return;a=c.href||"";a=a.replace(/-{2,}/g,"-");b=a;var d="",e="";if(b){var e=document.createElement("a"),f=t.location;b.indexOf("http")!==0&&b.indexOf("javascript")!==0&&(b=f.protocol+b);e.href=b;d=e.hostname;e=e.protocol;if(d==="")d=f.hostname;if(e===
"")e=f.protocol;e==="javascript:"&&(d="")}if(!(d!==t.location.hostname||e==="javascript:")){b=c;d=b.offsetLeft;c=b.offsetTop;f=o;for(e=b.offsetParent;b&&b!==g&&b!==document.body;){if(b===e)d+=b.offsetLeft,c+=b.offsetTop,e=b.offsetParent;var k=b,i=g;i=t.getComputedStyle?(k=t.getComputedStyle(k,m))&&(k.position||k.getPropertyValue("position")):k.currentStyle?k.currentStyle.position:k.style&&k.style.position;if((i||"")==="fixed"){f=l;break}b=b.parentElement}f&&(d+=0,c+=0);b=d;this.d.update("_chartbeat5",
[b,c,encodeURIComponent(this.a.path),encodeURIComponent(a)].join(","),6.944444444444445E-4,o,g,5)}}};
function ia(a){var b=a.d.b("_chartbeat5");if(!b)return m;var b=b.split("::"),c=b.length,d,e;if(c===1)d=b[0].split(","),e=0;else{var f,k=t.location.href;w(b,function(a,b){var c=b.split(","),q=ca(k,decodeURIComponent(c[3]));if(q===0)return d=c,e=a,o;if(f===g||q<f)f=q,d=c,e=a})}b.splice(e,1);a.d.create("_chartbeat5",b.join("::"),6.944444444444445E-4);return{left:d[0],top:d[1],path:decodeURIComponent(d[2]),L:c}};if(!t.pSUPERFLY){var $=new Z(new D);t.pSUPERFLY=$;Z.prototype.virtualPage=Z.prototype.Z;Z.prototype.activity=Z.prototype.P;U($);var ja=L.c(l);ja&&(z(t,"message",ea),ja.getItem("_cb_ip")&&M())};})();
